# -*- coding: utf-8 -*-
"""churn_model.pkl.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTg4ZwNM6kc8cIgGvCz2XDVXbyhsa1P4
"""

# ============================================================
# SAVE CUSTOMER CHURN MODEL
# ============================================================

import joblib
import os

# Check that the trained model exists
print("Checking trained model...")

print("Model found:", type(model))

# Save the trained model
joblib.dump(model, "churn_model.pkl")

# Check that the file was created
if os.path.isfile("churn_model.pkl"):
    print("\n✅ SUCCESS!")
    print("churn_model.pkl has been created.")
    print("File size:", os.path.getsize("churn_model.pkl"), "bytes")

    # Test loading the saved model
    saved_model = joblib.load("churn_model.pkl")

    print("✅ Model loaded successfully.")
    print("Saved model type:", type(saved_model))

else:
    print("\n❌ ERROR: churn_model.pkl was not created.")

import os

print("Searching for saved model files...\n")

for root, dirs, files in os.walk("."):
    for file in files:
        if file.lower().endswith((".pkl", ".joblib")):
            path = os.path.join(root, file)
            print(path, "->", os.path.getsize(path), "bytes")

# ============================================================
# CUSTOMER CHURN ML - COMPLETE MODEL TRAINING
# Creates a REAL churn_model.pkl
# ============================================================

import os
import joblib
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("=" * 70)
print("CUSTOMER CHURN ML - COMPLETE TRAINING")
print("=" * 70)


# ============================================================
# STEP 1 - FIND DATASET
# ============================================================

if "df" in globals() and isinstance(df, pd.DataFrame):
    df_model = df.copy()
    print("\n✅ Dataset found: df")

elif "data" in globals() and isinstance(data, pd.DataFrame):
    df_model = data.copy()
    print("\n✅ Dataset found: data")

else:
    raise Exception(
        "❌ Dataset not found. Your dataframe must be named df or data."
    )

print("Dataset shape:", df_model.shape)


# ============================================================
# STEP 2 - FIND CHURN TARGET COLUMN
# ============================================================

churn_columns = [
    col for col in df_model.columns
    if "churn" in str(col).lower()
]

if len(churn_columns) == 0:
    raise Exception(
        "❌ Churn column was not found.\n"
        "Available columns are:\n"
        + str(df_model.columns.tolist())
    )

target_column = churn_columns[0]

print("\n✅ Target column:", target_column)


# ============================================================
# STEP 3 - CLEAN COLUMN NAMES
# ============================================================

df_model.columns = [
    str(col).strip()
    for col in df_model.columns
]

# Re-check target after cleaning
target_matches = [
    col for col in df_model.columns
    if "churn" in col.lower()
]

target_column = target_matches[0]

print("Using target:", target_column)


# ============================================================
# STEP 4 - CLEAN TOTALCHARGES IF PRESENT
# ============================================================

if "TotalCharges" in df_model.columns:
    df_model["TotalCharges"] = pd.to_numeric(
        df_model["TotalCharges"],
        errors="coerce"
    )

if "totalcharges" in df_model.columns:
    df_model["totalcharges"] = pd.to_numeric(
        df_model["totalcharges"],
        errors="coerce"
    )


# ============================================================
# STEP 5 - REMOVE ID COLUMNS
# ============================================================

id_columns = []

for col in df_model.columns:
    col_lower = col.lower()

    if (
        col_lower in ["customerid", "customer_id", "id"]
        or col_lower.endswith("_id")
    ):
        id_columns.append(col)

if id_columns:
    df_model = df_model.drop(columns=id_columns)
    print("\nRemoved ID columns:", id_columns)


# ============================================================
# STEP 6 - REMOVE ROWS WITH MISSING TARGET
# ============================================================

df_model = df_model.dropna(subset=[target_column])


# ============================================================
# STEP 7 - CONVERT TARGET TO 0/1
# ============================================================

y_raw = df_model[target_column]

print("\nOriginal target values:")
print(y_raw.value_counts())

# Handle common Telco values: Yes / No
if y_raw.dtype == "object":

    y_clean = (
        y_raw
        .astype(str)
        .str.strip()
        .str.lower()
    )

    unique_values = set(y_clean.dropna().unique())

    if unique_values.issubset({"yes", "no"}):
        y = y_clean.map({
            "no": 0,
            "yes": 1
        })

    elif unique_values.issubset({"true", "false"}):
        y = y_clean.map({
            "false": 0,
            "true": 1
        })

    elif unique_values.issubset({"churn", "no churn"}):
        y = y_clean.map({
            "no churn": 0,
            "churn": 1
        })

    else:
        # Generic binary encoding
        values = list(y_clean.dropna().unique())

        if len(values) != 2:
            raise Exception(
                "❌ Target is not binary. Values found: "
                + str(values)
            )

        mapping = {
            values[0]: 0,
            values[1]: 1
        }

        y = y_clean.map(mapping)

        print("Target mapping:", mapping)

else:
    unique_values = sorted(y_raw.dropna().unique())

    if len(unique_values) != 2:
        raise Exception(
            "❌ Target is not binary. Values found: "
            + str(unique_values)
        )

    mapping = {
        unique_values[0]: 0,
        unique_values[1]: 1
    }

    y = y_raw.map(mapping)

    print("Target mapping:", mapping)


# Remove rows where target conversion failed
valid_rows = y.notna()

df_model = df_model.loc[valid_rows].copy()
y = y.loc[valid_rows].astype(int)


# ============================================================
# STEP 8 - CREATE FEATURES
# ============================================================

X = df_model.drop(columns=[target_column])

print("\nNumber of features:", X.shape[1])
print("Number of samples:", X.shape[0])


# ============================================================
# STEP 9 - IDENTIFY NUMERIC AND CATEGORICAL FEATURES
# ============================================================

numeric_features = X.select_dtypes(
    include=["int64", "int32", "float64", "float32"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

print("\nNumeric features:")
print(numeric_features)

print("\nCategorical features:")
print(categorical_features)


# ============================================================
# STEP 10 - BUILD PREPROCESSING PIPELINE
# ============================================================

numeric_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=False
            )
        )
    ]
)

preprocessor = ColumnTransformer(
    transformers=[
        (
            "numeric",
            numeric_pipeline,
            numeric_features
        ),
        (
            "categorical",
            categorical_pipeline,
            categorical_features
        )
    ],
    remainder="drop"
)


# ============================================================
# STEP 11 - CREATE MACHINE LEARNING MODEL
# ============================================================

classifier = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=42
)

model = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "classifier",
            classifier
        )
    ]
)


# ============================================================
# STEP 12 - TRAIN / TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))


# ============================================================
# STEP 13 - TRAIN MODEL
# ============================================================

print("\nTraining model...")

model.fit(X_train, y_train)

print("✅ Model training completed!")


# ============================================================
# STEP 14 - PREDICTION
# ============================================================

y_pred = model.predict(X_test)

y_probability = model.predict_proba(X_test)[:, 1]


# ============================================================
# STEP 15 - EVALUATION
# ============================================================

accuracy = accuracy_score(y_test, y_pred)

precision = precision_score(
    y_test,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_test,
    y_pred,
    zero_division=0
)

f1 = f1_score(
    y_test,
    y_pred,
    zero_division=0
)

print("\n" + "=" * 70)
print("MODEL PERFORMANCE")
print("=" * 70)

print(f"Accuracy  : {accuracy:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")
print(f"F1 Score  : {f1:.4f}")

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred,
        zero_division=0
    )
)

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


# ============================================================
# STEP 16 - SAVE THE COMPLETE PIPELINE
# ============================================================

MODEL_FILE = "churn_model.pkl"

joblib.dump(model, MODEL_FILE)


# ============================================================
# STEP 17 - VERIFY SAVED MODEL
# ============================================================

print("\n" + "=" * 70)
print("MODEL SAVING")
print("=" * 70)

if os.path.exists(MODEL_FILE):

    file_size = os.path.getsize(MODEL_FILE)

    print("✅ Model saved successfully!")
    print("File:", MODEL_FILE)
    print("Size:", file_size, "bytes")

    # Load model again
    loaded_model = joblib.load(MODEL_FILE)

    print("✅ Saved model loaded successfully!")
    print("Model type:", type(loaded_model))

    # Test loaded model
    test_prediction = loaded_model.predict(X_test.iloc[:1])

    print("Test prediction:", test_prediction[0])

    test_probability = loaded_model.predict_proba(
        X_test.iloc[:1]
    )[0]

    print("Test probabilities:", test_probability)

else:

    raise Exception(
        "❌ churn_model.pkl was not created."
    )


# ============================================================
# STEP 18 - FINAL RESULT
# ============================================================

print("\n" + "=" * 70)
print("🎉 COMPLETE!")
print("=" * 70)

print("""
Your real trained model is now:

    churn_model.pkl

This file contains:
    ✅ Preprocessing
    ✅ Feature encoding
    ✅ Feature scaling
    ✅ Trained Logistic Regression model
    ✅ Prediction probabilities

Next step:
    Use this churn_model.pkl with FastAPI.
""")